$axure.loadCurrentPage({
  "url":"幻灯片效果.html",
  "generationDate":new Date(1509935910272.15),
  "isCanvasEnabled":false,
  "variables":["path",
"sortfilter"],
  "page":{
    "packageId":"ac63d044274e4ec3a322312a5052f424",
    "type":"Axure:Page",
    "name":"幻灯片效果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fc30dd939f1a4328bc065a50dcdb531b",
          "label":"porter",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":310},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"784c61fdbd6f4ebc997f0f8e7d4bee2d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"928d4ee2ff3a401fb86e7d882916217c",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"435d158033cd435d8cf117b209c69f87",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u1.png"}},
{
                  "id":"beeeaf450fe24f0eb2a6f706114e6976",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":47,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82d8b61c6e83473c89a99723669f41ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":47,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"01a752bbd1ea4d82a0a7eeb46e87e43f",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9cc8fb14fd7f433981b553fae1b473af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":93,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"995c083da3d44d0e9fbdd8e39ade7b5c",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f5d0d24e4874136bb18104d8cd601ab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"447ee8db2f984b048c43eb3a6e69ebc5",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0c245c53e70143deabb9a956ceaa4f61",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a3449c28145b436092e289cbc11cb9f1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"ea50cf3df8434818888b73802bc71b5e",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "location":{
                      "x":47,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4ad2abae2a094e69bf01016ce9dbe381",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "location":{
                          "x":47,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u1.png"}},
{
                  "id":"50802fe207cc474f91e8efba310e1568",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1da9f254488447d8a38fb62136bcfac1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":93,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"550be1e9f0254af097a89595f3cb9407",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7fc7258dd2ba4e04b170b7048b597f74",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"52b2d5acd2f647f0baac38fbc566e801",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1f1d5b1f0cf24bd1a0e1f92074facdab",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"344dc8e62b1940308eba8b2ddba60536",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"b1e50bcae8624d569da09658107b74de",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":47,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"271d7643efc94d1d985a6ef8c37a07b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":47,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"f458d944ff7a4383bedb19ad4ad9ac2f",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8254ca3ceac94d6bb3f50d4bcfa22d25",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "location":{
                          "x":93,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u1.png"}},
{
                  "id":"a2e730a43e524de18f1f482e897ec568",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"193cdf06d9274458beb1599b4c0b4745",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"f7796219655540a5b941fdd731390363",
              "label":"State4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"41d13708e5f441adbb5f0cde6d8a4ce7",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e1899bbf4fc4279a934229860e6e2b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"7ccfeb64edcc4cbf93125594a3bdb368",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":47,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac61c93eed944a36b69bb791f58138c8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":47,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"026cb08f5ec94d698c9394eb7f9c2b78",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66a9a1e21cd44260bba7b28f1baf211f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":93,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"e2eb2a3a791745aca96595508f07f4b0",
                  "label":"",
                  "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4846dd4597a43838ee06042389b6286",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc30dd939f1a4328bc065a50dcdb531b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "location":{
                          "x":140,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"52d77a58e14c4875a138c040a259b05b",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":60},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"eb224de61ec8403681e4117cf5736b07",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"51e52b28b8b34b7b8cfbd4019a28f0d8",
                  "label":"",
                  "parentDynamicPanel":"52d77a58e14c4875a138c040a259b05b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82933bc04d6e4e6990309a4f18df6b4d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"52d77a58e14c4875a138c040a259b05b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":230}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u34.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"741d32a5268442309e40fc0b91e88a38",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"66f6a0bfae7d4031945653cdb63f05dc",
                  "label":"",
                  "parentDynamicPanel":"52d77a58e14c4875a138c040a259b05b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b55043de0d854a01840570bab92f1c15",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"52d77a58e14c4875a138c040a259b05b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":230}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u36.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ace920f35af74e0ca69a9dc8c4686d99",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3f37ffbc8b024175bf62a0c83a5c5854",
                  "label":"",
                  "parentDynamicPanel":"52d77a58e14c4875a138c040a259b05b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5303520a31444c3194de84eb140c139c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"52d77a58e14c4875a138c040a259b05b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":230}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u38.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"4baf722581f64078b593df5f809c09b1",
              "label":"State4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"52092118385743fe9128be5c7fb9f87f",
                  "label":"",
                  "parentDynamicPanel":"52d77a58e14c4875a138c040a259b05b",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"78e644d710ad4c3a8e00118c97e67683",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"52d77a58e14c4875a138c040a259b05b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":230}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u40.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"9c5fb6cb890a4d99a3efd2c728a2eca1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFF3F3F3},
{
                  "color":0xFFE7E7E7},
{
                  "color":0xFFE7E7E7}]},
            "location":{
              "x":90,
              "y":185},
            "size":{
              "width":30,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34b454ea18b24ef5b514c1335d59dcdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFF3F3F3},
{
                      "color":0xFFE7E7E7},
{
                      "color":0xFFE7E7E7}]},
                "location":{
                  "x":90,
                  "y":185},
                "size":{
                  "width":30,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/幻灯片效果/u42.png"}},
{
          "id":"8ab710ee6a274578b5d15fcb757e36ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":100,
              "y":190},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d1661cfb50b4f389772a86e307637ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":100,
                  "y":190},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/幻灯片效果/u44.png"}},
{
          "id":"c4df334b583e4a20a747c0181a8f7b3a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":115,
              "y":185},
            "size":{
              "width":10,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set porter to Previous wrap,<br>(Dynamic Panel) to Previous wrap",
                      "panelsToStates":[{
                          "panelPath":["fc30dd939f1a4328bc065a50dcdb531b"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}},
{
                          "panelPath":["52d77a58e14c4875a138c040a259b05b"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幻灯片效果/u46_line.png"}},
{
          "id":"544a80182ff34a2bb4abede34d5042c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFF3F3F3},
{
                  "color":0xFFE7E7E7},
{
                  "color":0xFFE7E7E7}]},
            "location":{
              "x":575,
              "y":185},
            "size":{
              "width":30,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d59f0f63bf89444ba7c3f3ab69de1053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFF3F3F3},
{
                      "color":0xFFE7E7E7},
{
                      "color":0xFFE7E7E7}]},
                "location":{
                  "x":575,
                  "y":185},
                "size":{
                  "width":30,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/幻灯片效果/u47.png"}},
{
          "id":"c4a13ed9962e499ab75644b0f859b60d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":585,
              "y":190},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b64d1a2870a46cc885003942d6b16b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":585,
                  "y":190},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to Next wrap,<br>porter to Next wrap",
                      "panelsToStates":[{
                          "panelPath":["52d77a58e14c4875a138c040a259b05b"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}},
{
                          "panelPath":["fc30dd939f1a4328bc065a50dcdb531b"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/幻灯片效果/u49.png"}},
{
          "id":"44ac828b77934d4db04ed32ae5332fe8",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":571,
              "y":185},
            "size":{
              "width":10,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/幻灯片效果/u46_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fc30dd939f1a4328bc065a50dcdb531b":{
      "scriptId":"u0"},
    "928d4ee2ff3a401fb86e7d882916217c":{
      "scriptId":"u1"},
    "435d158033cd435d8cf117b209c69f87":{
      "scriptId":"u2"},
    "beeeaf450fe24f0eb2a6f706114e6976":{
      "scriptId":"u3"},
    "82d8b61c6e83473c89a99723669f41ce":{
      "scriptId":"u4"},
    "01a752bbd1ea4d82a0a7eeb46e87e43f":{
      "scriptId":"u5"},
    "9cc8fb14fd7f433981b553fae1b473af":{
      "scriptId":"u6"},
    "995c083da3d44d0e9fbdd8e39ade7b5c":{
      "scriptId":"u7"},
    "7f5d0d24e4874136bb18104d8cd601ab":{
      "scriptId":"u8"},
    "0c245c53e70143deabb9a956ceaa4f61":{
      "scriptId":"u9"},
    "a3449c28145b436092e289cbc11cb9f1":{
      "scriptId":"u10"},
    "ea50cf3df8434818888b73802bc71b5e":{
      "scriptId":"u11"},
    "4ad2abae2a094e69bf01016ce9dbe381":{
      "scriptId":"u12"},
    "50802fe207cc474f91e8efba310e1568":{
      "scriptId":"u13"},
    "1da9f254488447d8a38fb62136bcfac1":{
      "scriptId":"u14"},
    "550be1e9f0254af097a89595f3cb9407":{
      "scriptId":"u15"},
    "7fc7258dd2ba4e04b170b7048b597f74":{
      "scriptId":"u16"},
    "1f1d5b1f0cf24bd1a0e1f92074facdab":{
      "scriptId":"u17"},
    "344dc8e62b1940308eba8b2ddba60536":{
      "scriptId":"u18"},
    "b1e50bcae8624d569da09658107b74de":{
      "scriptId":"u19"},
    "271d7643efc94d1d985a6ef8c37a07b5":{
      "scriptId":"u20"},
    "f458d944ff7a4383bedb19ad4ad9ac2f":{
      "scriptId":"u21"},
    "8254ca3ceac94d6bb3f50d4bcfa22d25":{
      "scriptId":"u22"},
    "a2e730a43e524de18f1f482e897ec568":{
      "scriptId":"u23"},
    "193cdf06d9274458beb1599b4c0b4745":{
      "scriptId":"u24"},
    "41d13708e5f441adbb5f0cde6d8a4ce7":{
      "scriptId":"u25"},
    "4e1899bbf4fc4279a934229860e6e2b0":{
      "scriptId":"u26"},
    "7ccfeb64edcc4cbf93125594a3bdb368":{
      "scriptId":"u27"},
    "ac61c93eed944a36b69bb791f58138c8":{
      "scriptId":"u28"},
    "026cb08f5ec94d698c9394eb7f9c2b78":{
      "scriptId":"u29"},
    "66a9a1e21cd44260bba7b28f1baf211f":{
      "scriptId":"u30"},
    "e2eb2a3a791745aca96595508f07f4b0":{
      "scriptId":"u31"},
    "e4846dd4597a43838ee06042389b6286":{
      "scriptId":"u32"},
    "52d77a58e14c4875a138c040a259b05b":{
      "scriptId":"u33"},
    "51e52b28b8b34b7b8cfbd4019a28f0d8":{
      "scriptId":"u34"},
    "82933bc04d6e4e6990309a4f18df6b4d":{
      "scriptId":"u35"},
    "66f6a0bfae7d4031945653cdb63f05dc":{
      "scriptId":"u36"},
    "b55043de0d854a01840570bab92f1c15":{
      "scriptId":"u37"},
    "3f37ffbc8b024175bf62a0c83a5c5854":{
      "scriptId":"u38"},
    "5303520a31444c3194de84eb140c139c":{
      "scriptId":"u39"},
    "52092118385743fe9128be5c7fb9f87f":{
      "scriptId":"u40"},
    "78e644d710ad4c3a8e00118c97e67683":{
      "scriptId":"u41"},
    "9c5fb6cb890a4d99a3efd2c728a2eca1":{
      "scriptId":"u42"},
    "34b454ea18b24ef5b514c1335d59dcdf":{
      "scriptId":"u43"},
    "8ab710ee6a274578b5d15fcb757e36ec":{
      "scriptId":"u44"},
    "0d1661cfb50b4f389772a86e307637ab":{
      "scriptId":"u45"},
    "c4df334b583e4a20a747c0181a8f7b3a":{
      "scriptId":"u46"},
    "544a80182ff34a2bb4abede34d5042c8":{
      "scriptId":"u47"},
    "d59f0f63bf89444ba7c3f3ab69de1053":{
      "scriptId":"u48"},
    "c4a13ed9962e499ab75644b0f859b60d":{
      "scriptId":"u49"},
    "5b64d1a2870a46cc885003942d6b16b6":{
      "scriptId":"u50"},
    "44ac828b77934d4db04ed32ae5332fe8":{
      "scriptId":"u51"}}});