$axure.loadCurrentPage({
  "url":"图片轮播.html",
  "generationDate":new Date(1509935911828.84),
  "isCanvasEnabled":false,
  "variables":["path",
"sortfilter"],
  "page":{
    "packageId":"b54e067280f545afbfee6dbfbea31331",
    "type":"Axure:Page",
    "name":"图片轮播",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b3df970c87d74f409214e9cdcc72d565",
          "label":"porter",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":310},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"67e42feb253b462bb2489758376c42c7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f4a41345fa324f60b55da018a8ae0916",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be7aed8759aa47d9a78cbe262e3c3c29",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u1.png"}},
{
                  "id":"4fe6e2b0efab4420b358b0ec4060a53f",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":47,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9859f76f5bb4d958ce53d948e42a81b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":47,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"62e09ffcc5624bde8f92f11161a534bb",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5f2d61e576cf47b288c2c23d0e09d6c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":93,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"c84e281302414a8498ec22c466842828",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c2add8ca03d44eba35d596de8efb797",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"f9cdd9144b7f46169326bec783038c6b",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c522d034213944b798ab39dd7f4a4ceb",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b865c7401be48589bb9cffa9182dd2d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"0af89032b9b146e5a8427ea07a07e98f",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "location":{
                      "x":47,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9acf6762b19f4ffeabf017a50373d6d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "location":{
                          "x":47,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u1.png"}},
{
                  "id":"c2143a3f3a5a49c58c4e1290e01f37e0",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f55ee1b42fed4175950c74faba2af790",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":93,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"7c38fd5b72894280839ab392d1cfcf03",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"04ee480df20949789ba87b9c094ad014",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"453f6616862a48dbbb58949c4487aa49",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bac50790fd3a4f9aa9887105caa8fe57",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c11ed10c5ecc4109a0e1b50863e4c9d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"22df2ce78c4d40258e902515be8fef57",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":47,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"96980f804a0e4647b37d278258aa598c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":47,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"7a8967d5f92f43068b2c6077bb382b21",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c5dd44861c04d19aa72beb6d120879e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "location":{
                          "x":93,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u1.png"}},
{
                  "id":"8abfca167cc44d4fb70294113d93a017",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"165695287e2d4e5c99fb3b514bfd769b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"a058ad25e74a4deab933c34501775a30",
              "label":"State4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c926ebf936b34b6782586f3230708278",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8a7ebf04af694e3abd8e202c7bc8a84a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"e5c9221334854dfaba1293a767b2854e",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":47,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"22f3d71f624d4b608f5a1418d6245dde",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":47,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"806b271c5bfa49bf81715bd41b12ba2e",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09840a69bb0a4d88b4bd9b1f34bafc38",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":93,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u3.png"}},
{
                  "id":"2acc9124be964666adf9696963f67067",
                  "label":"",
                  "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "location":{
                      "x":140,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"822b2cc24b0d4146b83a70a8355be99b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b3df970c87d74f409214e9cdcc72d565",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "location":{
                          "x":140,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"0eac1f749c114c19ada811f1439f1986",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":60},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set porter to Next fade out 500ms fade in 500ms wrap repeat every 2000 ms,<br>(Dynamic Panel) to Next slide left out 500ms slide left in 500ms wrap repeat every 2000 ms",
                      "panelsToStates":[{
                          "panelPath":["b3df970c87d74f409214e9cdcc72d565"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":2000,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}},
{
                          "panelPath":["0eac1f749c114c19ada811f1439f1986"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":2000,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"b8951f1f76d24540bc61c276dd5fd773",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b83deb58ce8d4b9ba783614448a5b697",
                  "label":"",
                  "parentDynamicPanel":"0eac1f749c114c19ada811f1439f1986",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0b43400101049f3a1107fe0b1270ba1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0eac1f749c114c19ada811f1439f1986",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":230}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u34.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"f34ad64ede0840bc839f11799deec1f6",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"15228d5c0eee4d0fb34895cb5d3e5295",
                  "label":"",
                  "parentDynamicPanel":"0eac1f749c114c19ada811f1439f1986",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b0072828e21448da339c6c7b4dce68b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0eac1f749c114c19ada811f1439f1986",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":230}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u36.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"510a8e67d90c4904842c31068483f799",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8e25a889bbcf432da2318133f6d78dcf",
                  "label":"",
                  "parentDynamicPanel":"0eac1f749c114c19ada811f1439f1986",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7679cf297c694df1bc1ecd377f1fc5fb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0eac1f749c114c19ada811f1439f1986",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":230}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u38.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0494d48a802945aa9d5898ec5bf75051",
              "label":"State4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"34f99709f9744164b3394421e95ef70c",
                  "label":"",
                  "parentDynamicPanel":"0eac1f749c114c19ada811f1439f1986",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"436acddd51d145d98cb626d90162c750",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0eac1f749c114c19ada811f1439f1986",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":230}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/幻灯片效果/u40.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "b3df970c87d74f409214e9cdcc72d565":{
      "scriptId":"u0"},
    "f4a41345fa324f60b55da018a8ae0916":{
      "scriptId":"u1"},
    "be7aed8759aa47d9a78cbe262e3c3c29":{
      "scriptId":"u2"},
    "4fe6e2b0efab4420b358b0ec4060a53f":{
      "scriptId":"u3"},
    "e9859f76f5bb4d958ce53d948e42a81b":{
      "scriptId":"u4"},
    "62e09ffcc5624bde8f92f11161a534bb":{
      "scriptId":"u5"},
    "5f2d61e576cf47b288c2c23d0e09d6c7":{
      "scriptId":"u6"},
    "c84e281302414a8498ec22c466842828":{
      "scriptId":"u7"},
    "1c2add8ca03d44eba35d596de8efb797":{
      "scriptId":"u8"},
    "c522d034213944b798ab39dd7f4a4ceb":{
      "scriptId":"u9"},
    "8b865c7401be48589bb9cffa9182dd2d":{
      "scriptId":"u10"},
    "0af89032b9b146e5a8427ea07a07e98f":{
      "scriptId":"u11"},
    "9acf6762b19f4ffeabf017a50373d6d9":{
      "scriptId":"u12"},
    "c2143a3f3a5a49c58c4e1290e01f37e0":{
      "scriptId":"u13"},
    "f55ee1b42fed4175950c74faba2af790":{
      "scriptId":"u14"},
    "7c38fd5b72894280839ab392d1cfcf03":{
      "scriptId":"u15"},
    "04ee480df20949789ba87b9c094ad014":{
      "scriptId":"u16"},
    "bac50790fd3a4f9aa9887105caa8fe57":{
      "scriptId":"u17"},
    "c11ed10c5ecc4109a0e1b50863e4c9d5":{
      "scriptId":"u18"},
    "22df2ce78c4d40258e902515be8fef57":{
      "scriptId":"u19"},
    "96980f804a0e4647b37d278258aa598c":{
      "scriptId":"u20"},
    "7a8967d5f92f43068b2c6077bb382b21":{
      "scriptId":"u21"},
    "5c5dd44861c04d19aa72beb6d120879e":{
      "scriptId":"u22"},
    "8abfca167cc44d4fb70294113d93a017":{
      "scriptId":"u23"},
    "165695287e2d4e5c99fb3b514bfd769b":{
      "scriptId":"u24"},
    "c926ebf936b34b6782586f3230708278":{
      "scriptId":"u25"},
    "8a7ebf04af694e3abd8e202c7bc8a84a":{
      "scriptId":"u26"},
    "e5c9221334854dfaba1293a767b2854e":{
      "scriptId":"u27"},
    "22f3d71f624d4b608f5a1418d6245dde":{
      "scriptId":"u28"},
    "806b271c5bfa49bf81715bd41b12ba2e":{
      "scriptId":"u29"},
    "09840a69bb0a4d88b4bd9b1f34bafc38":{
      "scriptId":"u30"},
    "2acc9124be964666adf9696963f67067":{
      "scriptId":"u31"},
    "822b2cc24b0d4146b83a70a8355be99b":{
      "scriptId":"u32"},
    "0eac1f749c114c19ada811f1439f1986":{
      "scriptId":"u33"},
    "b83deb58ce8d4b9ba783614448a5b697":{
      "scriptId":"u34"},
    "e0b43400101049f3a1107fe0b1270ba1":{
      "scriptId":"u35"},
    "15228d5c0eee4d0fb34895cb5d3e5295":{
      "scriptId":"u36"},
    "3b0072828e21448da339c6c7b4dce68b":{
      "scriptId":"u37"},
    "8e25a889bbcf432da2318133f6d78dcf":{
      "scriptId":"u38"},
    "7679cf297c694df1bc1ecd377f1fc5fb":{
      "scriptId":"u39"},
    "34f99709f9744164b3394421e95ef70c":{
      "scriptId":"u40"},
    "436acddd51d145d98cb626d90162c750":{
      "scriptId":"u41"}}});